name: Build and Deploy Vue

on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: eoussama/vue-pages-action@0.0.2
        with:
          username: 'SurendarAadhirai'
          reponame: 'dot-matrix'
          token: ${{ secrets.GITHUB_TOKEN }}
